### ISSUE TITLE
Yahoo Makes things a little complicated

### ISSUE THREAD

**Issue by justinpfister** [mazen/EtcpasswdOAuthBundle#10]
I have successfully implemented Oauth2 with Yahoo. The getAuthorizationUrl is a 2-step process where the first step provides a token to make a 'request_auth'.. and it also provides some 'secret tokens' which are not passed in from the Auth_Response but need to be used later on in the createTokenResponse method. I've solved this problem by using a Session variable. You can look at my patch-1 (YahooProvider->getAuthorizationUrl() and YahooProvider->createTokenResponse()) to see what I'm talking about.

I don't know if this is the best option OR if it's the only way to go. I also don't want to confuse the project by adding session support via Dependency Injection into the Provider class if it isn't necessary.

**Comment by mazen** [comment]
Yahoo is using OAuth v1 and not OAuth2. See Issue #1.

It is a bit trickier to implement (see http://oauth.net/core/1.0a/) and i'm not sure if it should be done at all since there already is a Twitter Auth Bundle.

In general, to support also twitter, all the session handling, token encryption et all should be added into some common functionality to be reused between different providers.

**Comment by justinpfister** [comment]
That makes more sense.. seem like they aren't OAuthV2 yet.. i was confused by the Yahoo oauth/v2/ url .. which you need to request Auth with..  https://api.login.yahoo.com/oauth/v2/request_auth
